#ifndef UART_CFG_H
#define UART_CFG_H

/*UART Transmitter enable*/
/*
UART_TRANSMITTE_ENABLE
UART_TRANSMITTE_DISABLE  
*/
#define UART_TRANSMITTE UART_TRANSMITTE_ENABLE

/*UART Receive enable*/
/*
UART_RECEIVE_ENABLE
UART_RECEIVE_DISABLE
*/
#define UART_RECEIVE UART_RECEIVE_ENABLE

/*UART Parity Modes*/
/*
UART_PARITY_DISABLE
UART_PARITY_EVEN
UART_PARITY_ODD
*/
 #define UART_PARITY_MODE UART_PARITY_DISABLE

 /*UART NO.Stop Bits*/
 /*
 UART_STOP_BIT_1
 UART_STOP_BIT_2
 */
#define UART_STOP_BIT   UART_STOP_BIT_1

/*UART Char Size*/
/*
UART_CHARCHTER_SIZE_5
UART_CHARCHTER_SIZE_6

UART_CHARCHTER_SIZE_7
UART_CHARCHTER_SIZE_8
UART_CHARCHTER_SIZE_9
*/
#define UART_CHARCHTER_SIZE UART_CHARCHTER_SIZE_8

#endif /*UART_CFG_H*/
